[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate
    '''
    Content-Security-Policy = '''
      default-src 'self' https://*.lunie.io https://*.netlify.app https://www.google-analytics.com https://monitoring.lunie.io:9000;
      connect-src 'self' https://api-iam.intercom.io https://widget.intercom.io wss://production-api.lunie.io/graphql https://production-api.lunie.io;
      img-src 'self' data: https://*.lunie.io https://*.netlify.app https://www.google-analytics.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.lunie.io https://*.netlify.app https://www.google-analytics.com https://api-iam.intercom.io;
      style-src 'self' 'unsafe-inline' https://*.lunie.io https://*.netlify.app;
      media-src 'self' https://*.lunie.io https://*.netlify.app blob:;
      object-src 'self' data: blob: https://*.lunie.io https://*.netlify.app https://www.google-analytics.com;
      manifest-src 'self' https://*.lunie.io https://*.netlify.app;
      worker-src 'none';
      frame-src 'self' https://api-iam.intercom.io;
      frame-ancestors 'self';
      base-uri 'self';
    '''

[context.production]
  command = "yarn buildsentry"

[context.deploy-preview]
  command = "yarn build --mode development"

[context.deploy-preview.environment]
  SENTRY_DSN = ""
  SENTRY_URL = ""
  SENTRY_TOKEN = ""

[context.deploy-preview.processing]
  skip_processing = true