version: 2

jobs:
  # Build Gaia from the SDK source code specified by tasks/build/Gaia/COMMIT.sh.
  buildGaia:
    docker:
      - image: circleci/golang

    steps:
      - checkout

      - restore_cache:
          key: v7-Gaia-{{ checksum "tasks/build/Gaia/COMMIT.sh" }}

      # If Gaia isn't in the cache then build it.
      - run: |
          if [ ! -d ~/target ]; then
            cd tasks/build/Gaia
            . COMMIT.sh
            TARGET=~/target ./build.sh
          fi

      - save_cache:
          key: v7-Gaia-{{ checksum "tasks/build/Gaia/COMMIT.sh" }}
          paths:
            - ~/target

      - persist_to_workspace:
          root: ~/target
          paths:
            - "*"

  changelogUpdated:
    docker:
      - image: circleci/node:9.4.0-browsers

    steps:
      - checkout

      - run: tasks/changelog-changed-check.sh

  testUnit:
    docker:
      - image: circleci/node:9.4.0-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-root-{{ checksum "package.json" }}
            - v3-dependencies-root-

      - run: yarn install

      - save_cache:
          paths:
            - yarn.lock
            - node_modules
          key: v3-dependencies-root-{{ checksum "package.json" }}

      - run: yarn run lint

      - run:
          name: Test
          command: yarn run test:unit
          no_output_timeout: 120

      - run:
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
          when: on_success

  testE2e:
    docker:
      - image: circleci/node:9.4.0-browsers

    environment:
      - BINARY_PATH: "/home/circleci/project/builds/Gaia/linux_amd64/gaiacli"
      - NODE_BINARY_PATH: "/home/circleci/project/builds/Gaia/linux_amd64/gaiad"

    steps:
      - checkout

      - attach_workspace:
          at: builds/Gaia

      - restore_cache:
          keys:
            - v2-dependencies-root-{{ checksum "package.json" }}
            - v2-dependencies-root-

      - run: yarn install

      - save_cache:
          paths:
            - yarn.lock
            - node_modules
          key: v2-dependencies-root-{{ checksum "package.json" }}

      - run:
          name: Test
          command: yarn run test:e2e
          no_output_timeout: 120

      - store_artifacts:
          path: testArtifacts
          when: on_fail

  # Create release.
  release:
    docker:
      - image: circleci/node:9.11.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-root-{{ checksum "package.json" }}
            - v2-dependencies-root-

      - run: yarn install
      - run: node tasks/createReleasePR.js

  # Publish the release to GitHub.
  publish:
    docker:
      - image: circleci/node:9.11.1

    steps:
      - checkout
      - run: sudo tasks/build/installWine.sh
      - run: yarn install

      - attach_workspace:
          at: builds/Gaia

      # download network configs
      - run: tasks/build/testnets/build.sh

      # build Voyager
      - run: node -e 'require("./tasks/build/build.js").buildAllPlatforms()'

      # test linux build
      - run: tar -zxvf ./builds/Voyager/Cosmos_Voyager-*-Linux.tar.gz
      - run: yarn test:exe "./Cosmos Voyager"

      - run: node tasks/publish.js

workflows:
  version: 2

  gaia-test-and-publish:
    jobs:
      - changelogUpdated:
          filters:
            branches:
              ignore: release

      - buildGaia:
          filters:
            branches:
              ignore: release

      - testUnit:
          filters:
            branches:
              ignore: release

      - testE2e:
          requires:
            - buildGaia
          filters:
            branches:
              ignore: release

      - publish:
          requires:
            - changelogUpdated
            - buildGaia
            - testUnit
            - testE2e
          filters:
            branches:
              only: develop
            tags:
              only: /^v.*/

  release:
    jobs:
      - release:
          filters:
            branches:
              only: release
