# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.4.0-browsers
    environment:
      - BINARY_PATH: "usr/bin/gaia"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-root-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-root-

      - run: yarn

      - save_cache:
          paths:
            - yarn.lock
            - node_modules
          key: v1-dependencies-root-{{ checksum "package.json" }}

      # - run: sudo wget https://tendermint-packages.interblock.io/centos/7/os/x86_64/RPM-GPG-KEY-Tendermint | sudo apt-key add
      - run: sudo wget -O /etc/apt/sources.list.d/tendermint.list https://tendermint-packages.interblock.io/debian/tendermint.list
      - run: sudo apt-get update && sudo apt-get install gaia
        
      - run: yarn run test
      - run: yarn run test:e2e
      - run: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
