name: Update existing droplet in Digital Ocean

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'api/**'
env:
  WORKING_DIRECTORY: ./api
jobs:
  test:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Build image
      run: docker build -t lunieapi . 
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Save file
      run: docker save lunieapi | gzip > lunieapi.tgz
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      with:
        source: "lunieapi.tgz,docker-compose.yml,Caddyfile"
        target: "/root/"
        host: ${{ secrets.HOST_STAGING }}
        username: root
        key: ${{ secrets.DO_PRIVATE_KEY }}
    # - name: prepare to push to Digital Ocean
    #   uses: appleboy/ssh-action@master
    #   env:
    #     USERNAME: my_username
    #     HOST: my_host
    #     SCRIPT: ~/deployment.sh
    #     KEY: ${{ secrets.DO_PRIVATE_KEY }}
    #   run: |
    #     mkdir -p ~/.ssh/
    #     echo "$SSH_PRIVATE_KEY" > ../private.key
    #     sudo chmod 600 ../private.key
    #     echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.DO_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa
    #     ssh-keyscan -H ${{ secrets.HOST_STAGING }} >> ~/.ssh/known_hosts
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.DO_PRIVATE_KEY }}
    #     SSH_KNOWN_HOSTS: 
    # - name: push to Digital Ocean
    #   run: |
    #     rsync -4 lunieapi.tgz root@${{ secrets.HOST_STAGING }}:~/
    #     rsync -4 docker-compose.yml root@${{ secrets.HOST_STAGING }}:~/
    #     rsync -4 Caddyfile root@${{ secrets.HOST_STAGING }}:~/
    #   working-directory: ${{env.WORKING_DIRECTORY}}
    # - name: Installing Docker Compose
    #   run: ssh root@${{ secrets.HOST_STAGING }} "sudo curl -L \"https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose; sudo chmod +x /usr/local/bin/docker-compose"
    #   working-directory: ${{env.WORKING_DIRECTORY}}
    # - name: Run on Digital Ocean
    #   run: ssh root@${{ secrets.HOST_STAGING }} "docker image prune -a -f; docker load < lunieapi.tgz;export HASURA_URL="https://staging-db.lunie.io/v1/graphql"; export HASURA_ADMIN_KEY="${{ secrets.LUNIE_STAGING_DB_KEY }}"; export SENTRY_DSN="${{ secrets.SENTRY_DSN_API_STAGING }}"; docker stack deploy -c docker-compose.yml lunieapi; docker service update --image lunieapi:latest --force lunieapi_lunieapi"
    #   working-directory: ${{env.WORKING_DIRECTORY}}
